version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: web_sentiment_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: web_sentiment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
